# Generated by Django 2.1.7 on 2019-03-13 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picassoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='CreatePost',
        ),
    ]
