# Generated by Django 2.1.7 on 2019-03-20 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picassoapp', '0003_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='UploadImage',
        ),
    ]
