# Generated by Django 2.1.7 on 2019-03-21 03:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('picassoapp', '0004_auto_20190320_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpost',
            name='liked',
            field=models.ManyToManyField(related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='liked',
            field=models.ManyToManyField(related_name='liked_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='createpost',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
