# Generated by Django 2.1.7 on 2019-03-21 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picassoapp', '0005_auto_20190321_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createpost',
            name='liked',
        ),
        migrations.DeleteModel(
            name='CreatePost',
        ),
    ]
