# Generated by Django 2.1.7 on 2019-03-23 05:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('picassoapp', '0006_auto_20190321_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
